version: '3.8'

services:
  db:
    image: mysql:9.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  nextjs:
    build: ./app
    container_name: nextjs-container
    env_file:
      - ./app/.env.local
    environment:
      DATABASE_URL: mysql://root:password@db:3306/mydb
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: random-secret-string
      NEXT_PUBLIC_API_URL: http://localhost:3000
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db


volumes:
  mysql-data:
