version: '3.8'

services:

  nextjs:
    build: ./app
    container_name: nextjs-container
    env_file:
      - ./app/.env.local
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3000
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "3000:3000"
