name: Deploy to Vercel  # ワークフローの名前

on:
  push:
    branches:
      - main          # mainブランチにプッシュされたときにワークフローをトリガーする

jobs:
  build:
    runs-on: ubuntu-latest   # ワークフローを実行する環境（OS）を指定。ここでは最新のUbuntu環境

    steps:
      - name: Check out code
        uses: actions/checkout@v2
        # 現在のリポジトリのコードをチェックアウト（取得）する
        # これにより、GitHub Actionsがコードを取得して、後のステップで使えるようになる

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # Docker Hubへのログイン。GitHub SecretsからDocker Hubの認証情報を取得する
        # Dockerイメージのビルド後にプッシュするために、ログインが必要

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/attmanage .
          docker push ${{ secrets.DOCKER_USERNAME }}/attmanage
        # Dockerイメージをビルドし、Docker Hubにプッシュするステップ
        # `docker build` でイメージをビルドし、`docker push` でリポジトリにプッシュする

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npx vercel --prod --token $VERCEL_TOKEN
        # Vercelへデプロイするステップ。環境変数としてVercelのトークンを使用
        # `npx vercel --prod` でVercelにプロダクションデプロイする
